# Site settings
title: "Daniël's Blog"
description: "Software engineering insights on C#, .NET, Azure, and sustainable architecture"
baseurl: "/blog"
url: "https://danielstegeman.github.io"

# Author information
author:
  name: "Daniël Stegeman"
  email: "Connect via LinkedIn"

# Multi-language settings
languages: [ "en", "nl" ]
default_lang: "en"
exclude_from_localizations: [ "javascript", "images", "css", "README.md" ]

# Build settings
markdown: kramdown
highlighter: rouge
theme: minima

# Jekyll plugins
plugins:
- jekyll-feed
- jekyll-sitemap
- jekyll-seo-tag
- jekyll-multiple-languages-plugin# Pagination
paginate: 5
paginate_path: "/page:num/"

# Collections
collections:
  posts:
    output: true
    permalink: /:year/:month/:day/:title/

# Exclude files from build
exclude:
- README.md
- Gemfile
- Gemfile.lock
- node_modules
- vendor

# Include future posts (set to false if you don't want to show future-dated posts)
future: false

# Timezone
timezone: UTC
