# Site settings
title: "Daniel's Blog"
description: "Thoughts, insights, and technical musings"
baseurl: "/blog"
url: "https://danielstegeman.github.io"

# Author information
author:
  name: "Daniel Stegeman"
  email: "your-email@example.com"

# Build settings
markdown: kramdown
highlighter: rouge
theme: minima

# Jekyll plugins
plugins:
- jekyll-feed
- jekyll-sitemap
- jekyll-seo-tag

# Pagination
paginate: 5
paginate_path: "/page:num/"

# Collections
collections:
  posts:
    output: true
    permalink: /:year/:month/:day/:title/

# Exclude files from build
exclude:
- README.md
- Gemfile
- Gemfile.lock
- node_modules
- vendor

# Include future posts (set to false if you don't want to show future-dated posts)
future: false

# Timezone
timezone: UTC
